settings:
  parallel: true

driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: "accept-silent"

platforms:
  - name: centos-7
  - name: debian-10
  - name: ubuntu-20.04

verifier:
  name: inspec

suites:
  - name: default
    attributes:
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
    run_list:
      - recipe[consul::default]
      - recipe[consul-template-cookbook::default]
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default/inspec