driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      box: centos/7
    run_list:
      - recipe[selinux::disabled]
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04
  - name: debian-9
    driver:
      box: debian/stretch64


suites:
  - name: default
    run_list:
      - recipe[consul::default]
      - recipe[consul-template-cookbook::default]
      - recipe[test::default]
    attributes:
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
    verifier:
      inspec_tests:
        - test/integration/default/inspec