services: docker

addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  matrix:
  - INSTANCE=centos
  - INSTANCE=debian
  - INSTANCE=ubuntu

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - export CHEF_LICENSE="accept-no-persist"
  - eval "$(chef shell-init bash)"
  - chef gem install kitchen-inspec
  
script: chef exec kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - cookstyle -D
      env: LINTING=1